In [1]:
import pickle as pkl
import pandas as pd
import os
from os.path import isfile, join

In [2]:
basedir = '/home/lms/ms/poc'

In [3]:
hist_data = pd.read_pickle(os.path.join(basedir, 'history.pkl')) # unique id = 2038827

In [4]:
hist_data

,sa_id,album_id,rating,category_id,watch_ratio,current_rate
0,205090929633,M01213B193PPV00,0.3731,B3054,0.6184,0.1278
1,205090929633,M01213H284PPV00,0.4639,B3054,0.8000,0.1278
2,205091284818,M011737453PPV00,0.5556,M011737453PPV00,1.0000,0.1111
3,205091284818,M0109C8A45PPV00,0.7195,M0109C8A45PPV00,0.8000,0.6389
4,205091284818,M0121CQ055PPV00,0.6173,B508W,0.3235,0.9111
...,...,...,...,...,...,...
63803415,M21110400009,M0121BB022PPV00,0.9184,B50O3,0.9924,0.8444
63803416,M21110400009,M0121CC004PPV00,0.9139,B567O,1.0000,0.8278
63803417,M21110400009,M0121BJ028PPV00,0.8500,B5665,1.0000,0.7000
63803418,M21110400009,M0121CA006PPV00,0.9084,B5665,1.0000,0.8167
63803419,M21110400009,M012211016PPV00,0.9722,B567O,1.0000,0.9444

In [5]:
hist_data.to_csv('/home/lms/ms/poc/history.csv', index=False)

In [1]:
# python 3.6으로 변경 필요
import pickle as pkl
import pandas as pd
import os
from os.path import isfile, join

In [2]:
data = pd.read_csv('/home/lms/ms/poc/history.csv')

/home/lms/anaconda3/envs/tf_deepctr/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data

,sa_id,album_id,rating,category_id,watch_ratio,current_rate
0,205090929633,M01213B193PPV00,0.3731,B3054,0.6184,0.1278
1,205090929633,M01213H284PPV00,0.4639,B3054,0.8000,0.1278
2,205091284818,M011737453PPV00,0.5556,M011737453PPV00,1.0000,0.1111
3,205091284818,M0109C8A45PPV00,0.7195,M0109C8A45PPV00,0.8000,0.6389
4,205091284818,M0121CQ055PPV00,0.6173,B508W,0.3235,0.9111
...,...,...,...,...,...,...
63803415,M21110400009,M0121BB022PPV00,0.9184,B50O3,0.9924,0.8444
63803416,M21110400009,M0121CC004PPV00,0.9139,B567O,1.0000,0.8278
63803417,M21110400009,M0121BJ028PPV00,0.8500,B5665,1.0000,0.7000
63803418,M21110400009,M0121CA006PPV00,0.9084,B5665,1.0000,0.8167
63803419,M21110400009,M012211016PPV00,0.9722,B567O,1.0000,0.9444

In [4]:
data.to_pickle('/home/lms/ms/poc/dataset/history.pkl')